Login
zhmurko-anastasi/MyDictionary pull request #1
Opened 2021-10-05 21:26 UTC by zhmurko-anastasi

Add login page UI
![image](https://user-images.githubusercontent.com/53611771/136339842-dfbe8eb8-09ae-45af-a15d-f36d7be67a06.png)

2021-10-06 04:40 UTC, just0110 commented on App.tsx
> +        {/* <StatusBar /> */}
Why so? Can you explain here a bit?

2021-10-06 04:41 UTC, just0110 commented on navigation/LinkingConfiguration.ts
> +// import { LinkingOptions } from '@react-navigation/native';
If you don't need this code - remove it. We have nice principles in programming for clean code. Here - YAGNI (google it)

2021-10-06 04:43 UTC, just0110 commented on navigation/index.tsx
> +// import TabTwoScreen from '../screens/TabTwoScreen';
Same here. It is a dead code. Or you're waiting for decomposing? :)

2021-10-06 04:44 UTC, just0110 commented
Second commit is unnecessary and interferes with reading

2021-10-06 05:12 UTC, serhiyburkow requested changes

2021-10-06 05:12 UTC, serhiyburkow commented on src/modules/NotFoundScreen.tsx
> +      <TouchableOpacity onPress={() => navigation.replace('Login')} style={styles.link}>
I see you are using everywhere Pressable. It's better to keep code consistent. May be it's better to use Pressable here also ?

2021-10-06 09:29 UTC, zhmurko-anastasi commented on navigation/index.tsx
> +// import ModalScreen from '../screens/ModalScreen';
Done

2021-10-06 09:48 UTC, zhmurko-anastasi commented on src/components/buttons/mainButton.tsx
> +      style={({ pressed }) => [
Done

2021-10-06 09:53 UTC, zhmurko-anastasi commented on src/modules/NotFoundScreen.tsx
> +      <TouchableOpacity onPress={() => navigation.replace('Login')} style={styles.link}>
This is code from expo-template, but I agree with you, will be done

2021-10-06 10:46 UTC, just0110 requested changes

2021-10-06 10:46 UTC, just0110 commented on App.tsx
> +        {/* <StatusBar /> */}
Do you know why we need StatusBar? That was a reason why i asked about commenting this

2021-10-06 10:46 UTC, just0110 commented on src/components/buttons/mainButton.tsx
> +export const MainButton: React.FC<Props> = ({
name of the file should also be like MainButton

2021-10-06 10:46 UTC, just0110 commented on src/components/buttons/mainButton.tsx
> +          style={styles.text}>
Keep your code clean. Why it is on next row?

2021-10-06 10:46 UTC, just0110 commented on src/components/index.tsx
> +export { MainButton } from './buttons/mainButton';
why MainButton is not exported by default from mainButton? the same question for inputWithIcon

2021-10-06 10:46 UTC, just0110 commented on src/components/styledText/linkText.tsx
> +export const LinkText: React.FC<Props> = ({
I see pressable here. It is not a text. It is rather LinkButton.

2021-10-06 10:46 UTC, just0110 commented on src/components/styledText/linkText.tsx
> +        <Text style={pressed ? ({...styles.link, ...styles.linkPressed, ...extraStyle}) : ({...styles.link, ...extraStyle}) }>
`[styles.link, styles.linkPressed, extraStyle]` ?

2021-10-06 10:46 UTC, just0110 commented on navigation/LinkingConfiguration.ts
> +// import { LinkingOptions } from '@react-navigation/native';
i see no changes unfortunately

2021-10-06 11:42 UTC, zhmurko-anastasi commented on App.tsx
> +        {/* <StatusBar /> */}
Yes, I do ) but I thought don't have the necessity to have it on the Login page, and other pages with visibility logic for statusBar I haven't got yet (but will be further) Or the StatusBar must be on all pages?

2021-10-07 07:40 UTC, serhiyburkow commented on src/components/inputs/inputWithIcon.tsx
> +    paddingTop: 10,
It's better to use paddingVertical: 10 instead of paddingTop: 10  + paddingBottom: 10 to keep code more readable

2021-10-07 07:46 UTC, serhiyburkow commented on src/modules/LoginScreen.tsx
> +  const handlerForgotButton = () => {
Question of naming. It can be handleForgotButton(WHAT? Click? hover? release?) or forgotButton(SOME ACTION)Handler.

2021-10-07 07:47 UTC, serhiyburkow commented on src/modules/LoginScreen.tsx
> +
Please remove empty space below. Code should be clean.

2021-10-08 14:33 UTC, merged