base navigation, default screens are added
zhmurko-anastasi/MyDictionary pull request #2
Opened 2021-10-08 16:24 UTC by zhmurko-anastasi

2021-10-09 08:33 UTC, serhiyburkow requested changes

2021-10-09 08:33 UTC, serhiyburkow commented on App.tsx
> +import * as React from 'react';
Great! Take care for the future :)

2021-10-09 08:33 UTC, serhiyburkow commented on navigation/index.tsx
> +  const getIconColor = (focused: boolean) => focused ? mainBlack : mainGrey;
You can make it simpler way while you don't need additional conditions: 
`
<Tab.Navigator screenOptions={() => ({
            tabBarActiveTintColor: 'tomato',
            tabBarInactiveTintColor: 'gray',
        })}
`

2021-10-09 08:33 UTC, serhiyburkow commented on src/modules/CreateScreen.tsx
> +      <Pressable onPress={() => navigation.replace('Login')} style={styles.link}>
I suggest you to create common component for button.

2021-10-09 08:33 UTC, serhiyburkow commented on types.tsx
> +  Root: NavigatorScreenParams<RootTabParamList> | undefined;
Always good to use enum for navigation names to explicitly avoid "silent" typos and to make possible refactoring easier. 

```
    [Routes.mainStack]: undefined;
    [Routes.dashboard]: undefined;

```

2021-10-11 13:54 UTC, zhmurko-anastasi commented on navigation/index.tsx
> +          tabBarIcon: ({ color }: { color: any }) => <Ionicons color={color}  size={30} name="home" />,
Done

2021-10-13 08:02 UTC, merged