Connect Apollo Client, created query & mutanions for User
zhmurko-anastasi/MyDictionary pull request #4
Opened 2021-10-30 13:01 UTC by zhmurko-anastasi

2021-11-01 15:24 UTC, serhiyburkow commented on src/config/apolloClient.tsx
> +const  uri = 'http://192.168.0.105:3000/graphql';
It's always good to move such things as URLs to separate config file.

2021-11-01 15:24 UTC, serhiyburkow commented on src/modules/login/graphql.ts
> +import { gql } from "@apollo/client";
I think (but I could be wrong) that name file as query name is good. For example: create_user.gql.ts

2021-11-01 17:27 UTC, zhmurko-anastasi commented on src/modules/login/graphql.ts
> +import { gql } from "@apollo/client";
I  will research this, thanks ))

2021-11-01 17:52 UTC, zhmurko-anastasi commented on src/config/index.tsx
>  }
@serhiyburkow  commit --amend

2021-11-01 19:43 UTC, serhiyburkow approved these changes

2021-11-02 08:42 UTC, Ragnarreck commented on src/config/apolloClient.tsx
> +import { ApolloClient, from, gql, InMemoryCache } from '@apollo/client';
Not something to fix, just to think of in the future: if youre following the modules architecture, it would be more logical to have `config/apollo/index.ts`

2021-11-02 08:43 UTC, Ragnarreck commented on src/config/index.tsx
> +const  uri = 'http://192.168.0.101:3000/graphql';
Ah I see. You better move it under the `apollo` module, cause right now if you will want to configure something else, you will face issues :)

2021-11-02 08:45 UTC, Ragnarreck commented on src/modules/profile/ProfileScreen.tsx
>    const pickImage = async () => {
I would wrap the `pickImage` with try/catch, but up to you

2021-11-02 08:45 UTC, Ragnarreck commented on src/modules/profile/ProfileScreen.tsx
> +      data['findOneUser'].image && setImage(data['findOneUser'].image)
Too much code. Can you try to shortify it?

2021-11-02 08:46 UTC, Ragnarreck requested changes
Good job! Left some comments.

2021-11-02 13:58 UTC, zhmurko-anastasi commented on src/config/apolloClient.tsx
> +const  uri = 'http://192.168.0.105:3000/graphql';
Done %

2021-11-02 13:59 UTC, zhmurko-anastasi commented on src/config/apolloClient.tsx
> +import { ApolloClient, from, gql, InMemoryCache } from '@apollo/client';
Yeah, thanks, made a separate folder for the Appollo client )

2021-11-02 14:00 UTC, zhmurko-anastasi commented on src/config/index.tsx
> +const  uri = 'http://192.168.0.101:3000/graphql';
Created a separated index.ts file for the constants )

2021-11-02 14:04 UTC, zhmurko-anastasi commented on src/modules/profile/ProfileScreen.tsx
>    const pickImage = async () => {
Done, thanks )

2021-11-02 14:10 UTC, zhmurko-anastasi commented on src/modules/profile/ProfileScreen.tsx
> +      data['findOneUser'].image && setImage(data['findOneUser'].image)
Of course, I'll try )

2021-11-02 15:45 UTC, Ragnarreck commented on src/config/apolloClient.tsx
> +import { ApolloClient, from, gql, InMemoryCache } from '@apollo/client';
Looks like you have two apollo configs now?

2021-11-02 15:47 UTC, Ragnarreck commented on src/config/index.tsx
> +}
Since it's a common export file (not sure why do u need it, but anyway), it would make sense to have a field called `apollo` with property `client` or at least rename it to `apolloClient`, because it's not clear what client is that.
```
export { apollo: { client } }
```

2021-11-02 15:49 UTC, Ragnarreck commented on src/modules/profile/ProfileScreen.tsx
>      setBcground(Asset.fromModule(require(DEFAULT_URI_BACKGROUD)).uri);
👍

2021-11-02 16:34 UTC, zhmurko-anastasi commented on src/config/apolloClient.tsx
> +import { ApolloClient, from, gql, InMemoryCache } from '@apollo/client';
fixed it!

2021-11-02 16:44 UTC, merged